package binarycrows.robot.SeasonCode.SubStateManagers.CANdle;

public enum CANdleStateRequest {
    RED,
    GREEN,
    BLUE,

    SHOOT_BAD_DISTANCE_TOO_HIGH,
    SHOOT_BAD_DISTANCE_WAY_TOO_HIGH,
    SHOOT_BAD_HOOD_DELTA_TOO_HIGH,
    SHOOT_BAD_TURRET_DELTA_TOO_HIGH,
    SHOOT_BAD_VELOCITY_TOO_HIGH,
    SHOOT_BAD_VELOCITY_WAY_TOO_HIGH,
    SHOOT_BAD_ACCELERATION_TOO_HIGH,
    SHOOT_BAD_WRONG_SIDE_OF_FIELD,
    SHOOT_GOOD,

    HOPPER_FULL,
    HOPPER_PARTIAL,
    HOPPER_EMPTY
}
